document.write('<html>');
document.write('');
document.write('<head>');
document.write('    <meta charset="utf-8" />');
document.write('    <meta http-equiv="X-UA-Compatible" content="chrome=1" />');
document.write('    <meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('    <title>IT Should Know</title>');
document.write('    <link rel="icon" href="https://google.com/favicon.ico" type="image/x-icon" />');
document.write('    <link href="./css/main.css" rel="stylesheet" type="text/css" />');
document.write('    <script src="./js/polyfills.js"></script>');
document.write('    <script src="./js/main.js"></script> </head>');
document.write('');
document.write('<body>');
document.write('    <div id="sidenav" style="display: none; padding-top: 50px;">');
document.write('        <button id="sidenavBtn">&#9776;</button>');
document.write('        <img id="profilePic" alt="An avatar that aims to represent the website owner" src="./img/avatar.png">');
document.write('    </div>');
document.write('    <div id="container">');
document.write('        <div id="output"></div>');
document.write('        <div id="input-line" class="input-line">');
document.write('            <div id="prompt" class="prompt-color"></div>&nbsp;');
document.write('            <div>');
document.write('                <input type="text" id="cmdline" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"');
document.write('                    autofocus/>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('    <a id="githubImg" target="_blank" href="https://github.com/j0shi77">');
document.write('        <img alt="Fork me on GitHub" src="./img/github_ribbon.png"> </a>');
document.write('</body>');
document.write('');
document.write('</html>');